apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qnjr2mw1p-go
  janus-idp.io/tekton: qnjr2mw1p-go
  backstage.io/kubernetes-id: qnjr2mw1p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qnjr2mw1p-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
